@host = gcp-ticketing.dev/api

# User Signup
POST {{host}}/users/signup
Content-Type: application/json

{
    "email": "user@mail.com",
    "password":"pqrstuv"
}

# checking 404 not found

###
GET {{host}}/users/signup/something_that_doesnot_exits
Content-Type: : application/json
###
POST {{host}}/users/signup/something_that_doesnot_exits
Content-Type: : application/json
